### PR TITLE
PC-226: Make Advanced filters UI more intuitive

### PR DESCRIPTION
**Pull request by veronikaslc**
Advanced filters are updated, except [translastion](https://github.com/phenotips/phenotips/blob/master/components/navigation/api/src/main/resources/ApplicationResources.properties) changes, which are minor.
@sdumitriu should they also be in the fix? If yes - where is the right place to put this `ApplicationResources.properties` file?

### CODE REVIEW

**Comment by sashaandjic** [comment]
Export dialog is also missing above mentioned filter fields
screen shot 2018-01-22 at 1 41 22 pm

**Comment by veronikaslc** [comment]
@sashaandjic codereview comments addressed

**Comment by sashaandjic** [comment]
suggestions for owner and collaborator fields are not present

**Comment by allasm** [comment]
I'm not even sure how to review this, a LOT of new velocity code (which as far as I understand is back-ported from Phenotips 1.4). It is very hard to tell if all of the code is ok and/or plugged in correctly. Don't see anything wrong so I would approve it given @sashaandjic has tested it

**Pull request merged**
