### PR TITLE
PT-2039: Add consents configuration to PhenomeCentral

### PR DESCRIPTION
**Pull request by antonkatz**

### CODE REVIEW

**Comment by sdumitriu** [comment]
Valid PR, needs reviews. @antonkatz this uses the consents code merged in master, right?

**Comment by allasm** [comment]
I can confirm it does (uses the consents code merged in master), and that given that new code PC wont work without this update

**Comment by antonkatz** [comment]
@sdumitriu That's correct.

**Comment by buske** [comment]
Looks good to me and seems to work.

**Pull request merged**
